---
- name: test sending message to Symphony Web Deployment chat room
  uri:
     url: "https://lordabbett-test.symphony.com/integration/v1/whi/simpleWebHookIntegration/59047a9ae4b0b8f3640ee6a6/59287ffee4b042436ffe25b8"
     method: POST
     headers:
          Content-Type: "application/xml"
     body: "
               <messageML>
                  New Web Site is online at http://lxtoolsb1-sopv/index.html
               </messageML>"
     body_format: raw
     validate_certs: no
     return_content: no
     follow_redirects: all
